### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by mrjshzk** [acegiak/Godot4TerrainShader#1]
I've been trying to use this plugin but can't figure it out. Can you write some documentation or make a tutorial please?

**Comment by acegiak** [comment]
https://github.com/acegiak/Godot4TerrainShader/commit/8572dc7811bf92976afe5f4a23713ba2925f28fc

Updated the readme document, added a demonstration gif, and added an example material. Let me know if that helps make things clearer?

**Comment by mrjshzk** [comment]
yes, this is great. thank you very much!!
